export const roomImageService: Record<string, string> = {
  "1": "/images/rooms/1.png",
  "2": "/images/rooms/2.png",
  "3": "/images/rooms/3.png",
  "4": "/images/rooms/4.png",
  "5": "/images/rooms/5.png",
  "6": "/images/rooms/6.png",
  "7": "/images/rooms/7.png",
  "8": "/images/rooms/8.png",
  "9": "/images/rooms/9.png",
  "10": "/images/rooms/10.png",
  "11": "/images/rooms/11.png",
  "12": "/images/rooms/12.png",
  "13": "/images/rooms/13.png",
  "14": "/images/rooms/14.png",
  "15": "/images/rooms/15.png",
  "16": "/images/rooms/16.png",
  "17": "/images/rooms/17.png",
  "18": "/images/rooms/18.png",
  "19": "/images/rooms/19.png",
  "20": "/images/rooms/20.png",
};
