export * from "./MainPage";
export * from "./SearchPage";
export * from "./HotelDetailsPage";
export * from "./LoginPage";
export * from "./RegisterPage";
export * from "./AdminPage";
export * from "./ProfilePage";
export * from "./ClerkPage";
export * from "./AboutPage";
